package com.bugsTeam.training.foodrunner

const val NETWORK_IP = "http://13.235.250.119/v2/"
const val REGISTER = "$NETWORK_IP/register/fetch_result"
const val LOGIN = "$NETWORK_IP/login/fetch_result"
const val FORGOT_PASSWORD = "$NETWORK_IP/forgot_password/fetch_result"
const val RESET_PASSWORD = "$NETWORK_IP/reset_password/fetch_result"
const val FETCH_RESTAURANTS = "$NETWORK_IP/restaurants/fetch_result"
const val PLACE_ORDER = "$NETWORK_IP/place_order/fetch_result"
const val FETCH_PREVIOUS_ORDERS = "$NETWORK_IP/orders/fetch_result/"
const val IS_LOGIN="isLoggedIn"
const val KEY_ADDRESS="address"
const val KEY_MOBILE="mobile_number"
const val KEY_PASSWORD="password"
const val KEY_EMAIL="email"
const val KEY_NAME="name"
const val KEY_ID="id"